const API="https://search.zemer.io";
const state={player:null,current:null,playing:false,timer:null};
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll(String.fromCharCode(34),"&quot;").replaceAll("'","&#39;");
const thumb=x=>x?.thumbnailUrl||x?.thumbnail||x?.thumbnailUrlSmall||x?.art||"";
const title=x=>x?.title||x?.name||"";
const artist=x=>x?.artistName||x?.artist||x?.author||"";
function normalize(v,kind){if(!v||typeof v!=="object")return null;return {...v,_kind:kind,_videoId:v.videoId||((kind==="songs"||kind==="videos"||kind==="singles")?v.id:"")};}
function flatten(v,k){return Array.isArray(v)?v.map(x=>normalize(x,k)).filter(Boolean):[];}
function render(data,q){const cats=data?.categories||{};const order=[["Songs",cats.songs],["Artists",cats.artists],["Albums",cats.albums],["Singles",cats.singles],["Videos",cats.videos],["Playlists",cats.playlists]];let html="",total=0;for(const pair of order){const name=pair[0],items=flatten(pair[1],name.toLowerCase());if(!items.length)continue;total+=items.length;html+="<section class=\"section\"><h2>"+esc(name)+"</h2>";for(const x of items){const image=thumb(x),can=!!x._videoId;html+="<div class=\"row\" data-item=\""+esc(JSON.stringify(x))+"\"><img class=\"art\" src=\""+esc(image)+"\" loading=\"lazy\"><div class=\"info\"><div class=\"title\">"+esc(title(x))+"</div><div class=\"sub\">"+esc(artist(x)||x.subtitle||"")+"</div></div>"+(can?"<button class=\"play\">▶</button>":"")+"</div>";}html+="</section>";}$("results").innerHTML=html;$("status").textContent=total?total+" results for “"+q+"”":"No results.";document.querySelectorAll(".row").forEach(row=>row.addEventListener("click",()=>{const item=JSON.parse(row.dataset.item);if(item._videoId)play(item);}));}
async function search(q){q=q.trim();if(!q)return;$("status").textContent="Searching…";$("results").innerHTML="";try{const r=await fetch(API+"/search?q="+encodeURIComponent(q)+"&allowFemale=0&kidZone=0&blockVideos=1&k=50",{headers:{Accept:"application/json"}});if(!r.ok)throw Error("HTTP "+r.status);render(await r.json(),q);}catch(e){console.error(e);$("status").textContent="Couldn’t search right now. Try again in a moment.";}}
$("form").addEventListener("submit",e=>{e.preventDefault();search($("q").value);});
function play(item){state.current=item;$("player").hidden=false;$("ptitle").textContent=title(item);$("psub").textContent=artist(item);$("part").src=thumb(item);if(!state.player){state.player=new YT.Player("yt",{height:"1",width:"1",videoId:item._videoId,playerVars:{autoplay:1,playsinline:1,controls:0,rel:0},events:{onReady:e=>{e.target.playVideo();tick();},onStateChange:e=>{state.playing=e.data===YT.PlayerState.PLAYING;$("pause").textContent=state.playing?"❚❚":"▶";}}});}else{state.player.loadVideoById(item._videoId);state.playing=true;$("pause").textContent="❚❚";tick();}}
function tick(){clearInterval(state.timer);state.timer=setInterval(()=>{if(!state.player||!state.player.getDuration)return;const d=state.player.getDuration()||0,c=state.player.getCurrentTime()||0;$("bar").style.width=d?(c/d*100)+"%":"0%";},500);}
$("pause").onclick=()=>{if(!state.player)return;if(state.playing){state.player.pauseVideo();state.playing=false;$("pause").textContent="▶";}else{state.player.playVideo();state.playing=true;$("pause").textContent="❚❚";}};